### PR TITLE
Implement ReferenceProvider for Find References

### PR DESCRIPTION
**Pull request by ikhwanhayat**
This is for issue #30

### CODE REVIEW

**Comment by DanTup** [comment]
Great! Thanks very much! :)

**Comment by DanTup** [comment]
This worked so well I thought it was worth pushing a little update out with it :-)

https://marketplace.visualstudio.com/items?itemName=DanTup.dart-code

**Comment by ikhwanhayat** [comment]
Nice! Glad to hear that. I'll try to work on some more issues. Might take some time tho, this is my first time doing a VS Code extension.

**Comment by DanTup** [comment]
Mine too; but the API has been really nice and easy! :)

Please add a note to the issue if you want to do anything (create a new issue if one doesn't exist) to ensure it's not something already being worked on.

Thanks again!

**Pull request merged**
