### PR TITLE
Make workspace symbol search case-insensitive

### PR DESCRIPTION
**Pull request by devoncarew**
- allow case insensitive search in the workspace symbol dialog
- add some common logic to convert from analysis server locations to vscode ones (fix https://github.com/DanTup/Dart-Code/issues/10)

screen shot 2016-08-06 at 12 00 20 am

### CODE REVIEW

**Comment by DanTup** [comment]
Great, thanks!

I think I'm actually using the wrong method here (top-level) as I would expect it to find methods in classes (for example). I presume this logic all applies the same if I change that? (#24).

**Comment by DanTup** [comment]
When I re-read this code, I was worried about the wildcards. It means "cat" will match "cart". However, VS Code seems to do further filtering on the results that come back and only allow missing characters if they're lowercase and preceed an uppercase character.

Eg:

- "TA" matches "TwitterApi"
- "twittera" matches "TwitterApi"
- "twitera" does match "TwitterApi" in the analyzer (I see the results come back in the debug window) but VS Code appears to hide the result

I think this actually works out really well for the user though I'm wondering whether on a large codebase it'd generate a lot of unnecessary results over the wire. Any thoughts @devoncarew?

**Comment by devoncarew** [comment]
Yeah, we're filtering results - all the top level symbols - and then vscode is applying a fuzzy match on top of that. I do like how it works out - it'll often show you the match you were thinking about w/o you having to be too precise.

I'm not super worried about the wire traffic - there are other parts of the protocol that are pretty verbose as well. We could measure it and get a sense of whether it's impacting the performance.

**Comment by DanTup** [comment]
Cool; you're more familiar with it than I so if you're not concerned, sounds good to me!

I'm not sure about only doing top-level results though, I posted in the [analyser-discuss group here](https://groups.google.com/a/dartlang.org/forum/#!topic/analyzer-discuss/conkKX7XiKI), would be interested in your opinion!

**Pull request merged**
